function [fitresult, gof] = createFit(xAxis, yAxis)
%CREATEFIT(XAXIS,YAXIS)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xAxis
%      Y Output: yAxis
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 11-Apr-2016 21:27:25


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( xAxis, yAxis );

% Set up fittype and options.
ft = fittype( '1-exp(-(x/a)^m)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.743132468124916 0.392227019534168];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'yAxis vs. xAxis', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel( 'xAxis' );
ylabel( 'yAxis' );
grid on


